### ISSUE TITLE
Issue with knex migration

### ISSUE THREAD

**Issue by ltsharma** [Bikranshu/express-react-boilerplate#9]
When i try to run npm run migrate the following error is coming up.

`
Error: ER_INVALID_DEFAULT: Invalid default value for 'updated_at'
    at Query.Sequence._packetToError (/Users/lts/Reaction-lab/express/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/lts/Reaction-lab/express/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/lts/Reaction-lab/express/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/lts/Reaction-lab/express/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/lts/Reaction-lab/express/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/lts/Reaction-lab/express/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/lts/Reaction-lab/express/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/lts/Reaction-lab/express/node_modules/mysql/lib/Connection.js:525:10)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:290:12)
    at readableAddChunk (_stream_readable.js:271:11)
    at Socket.Readable.push (_stream_readable.js:226:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:166:17)
    --------------------
    at Protocol._enqueue (/Users/lts/Reaction-lab/express/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/Users/lts/Reaction-lab/express/node_modules/mysql/lib/Connection.js:201:25)
    at /Users/lts/Reaction-lab/express/node_modules/knex/lib/dialects/mysql/index.js:144:18
    at Promise._execute (/Users/lts/Reaction-lab/express/node_modules/knex/node_modules/bluebird/js/release/debuggability.js:313:9)
    at Promise._resolveFromExecutor (/Users/lts/Reaction-lab/express/node_modules/knex/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/lts/Reaction-lab/express/node_modules/knex/node_modules/bluebird/js/release/promise.js:79:10)
    at Client_MySQL._query (/Users/lts/Reaction-lab/express/node_modules/knex/lib/dialects/mysql/index.js:135:12)
    at Client_MySQL.query (/Users/lts/Reaction-lab/express/node_modules/knex/lib/client.js:192:17)
    at /Users/lts/Reaction-lab/express/node_modules/knex/lib/transaction.js:232:21
    at tryCatcher (/Users/lts/Reaction-lab/express/node_modules/knex/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/Users/lts/Reaction-lab/express/node_modules/knex/node_modules/bluebird/js/release/method.js:39:29)
    at Client_MySQL.trxClient.query (/Users/lts/Reaction-lab/express/node_modules/knex/lib/transaction.js:229:33)
    at Runner.<anonymous> (/Users/lts/Reaction-lab/express/node_modules/knex/lib/runner.js:138:36)
    at Runner.tryCatcher (/Users/lts/Reaction-lab/express/node_modules/knex/node_modules/bluebird/js/release/util.js:16:23)
    at Runner.query (/Users/lts/Reaction-lab/express/node_modules/knex/node_modules/bluebird/js/release/method.js:15:34)
    at Runner.queryArray (/Users/lts/Reaction-lab/express/node_modules/knex/lib/runner.js:207:40)`

**Comment by takeshimouri** [comment]
I've solved in below codes

```server/migrations/20170715222060_create_users_table.js

table.datetime('created_at');
table.datetime('updated_at');

```
